site_name: Leonis
nav:
  - Accueil: "index.md"
  - Make your Leonis: "make.md"
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
plugins:
  - search
  - git-revision-date-localized
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LeonisLinks/Leonis
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Y9SvsWk26B
markdown_extensions:
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - admonition
extra_css:
  - extra.css